package dbx

import (
	"bytes"
	"context"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"hash/fnv"
	"io"
	"math"
	"net"
	"regexp"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"

	"github.com/paulmanoni/nifi/record"
)

// WriteMode selects how rows land in the target table.
type WriteMode string

const (
	ModeMerge       WriteMode = "merge"        // staged COPY + ON CONFLICT DO UPDATE
	ModeMergeIgnore WriteMode = "merge_ignore" // staged COPY + ON CONFLICT DO NOTHING
	ModeCopy        WriteMode = "copy"         // straight COPY
	ModeInsert      WriteMode = "insert"       // staged COPY + plain INSERT
)

// Target is a resolved destination table.
type Target struct {
	Schema  string
	Name    string
	Columns map[string]record.Column
	Order   []string
	PK      []string
	Created bool
}

// Ref returns the quoted, qualified table reference.
func (t *Target) Ref() string { return QuotePG(t.Schema) + "." + QuotePG(t.Name) }

// Display is schema.table for messages.
func (t *Target) Display() string { return t.Schema + "." + t.Name }

// LoadTarget introspects an existing table; nil when it does not exist.
func (p *PG) LoadTarget(ctx context.Context, schema, name string) (*Target, error) {
	var exists bool
	if err := p.Pool.QueryRow(ctx, `SELECT to_regclass($1) IS NOT NULL`, QuotePG(schema)+"."+QuotePG(name)).Scan(&exists); err != nil {
		return nil, err
	}
	if !exists {
		return nil, nil
	}
	meta, err := p.Describe(ctx, schema+"."+name)
	if err != nil {
		return nil, err
	}
	t := &Target{Schema: schema, Name: name, Columns: map[string]record.Column{}, PK: meta.PrimaryKey}
	for _, c := range meta.Columns {
		t.Columns[c.Name] = c
		t.Order = append(t.Order, c.Name)
	}
	return t, nil
}

// PGType maps a logical column to a PostgreSQL column type.
func PGType(c record.Column, sourceDialect string) string {
	if c.TargetType != "" {
		return c.TargetType
	}
	if sourceDialect == "postgres" && c.NativeType != "" && c.Type != record.Other && c.Type != record.Enum {
		return c.NativeType
	}
	switch c.Type {
	case record.Bool:
		return "boolean"
	case record.Int16, record.Year:
		return "smallint"
	case record.Int32:
		if c.AutoIncrement {
			return "bigint"
		}
		return "integer"
	case record.Int64:
		return "bigint"
	case record.Uint64:
		if c.AutoIncrement {
			// Surrogate keys never approach 2^63; bigint keeps the identity.
			return "bigint"
		}
		return "numeric(20,0)"
	case record.Float32:
		return "real"
	case record.Float64:
		return "double precision"
	case record.Decimal:
		if c.Precision > 0 && c.Precision <= 1000 {
			return fmt.Sprintf("numeric(%d,%d)", c.Precision, c.Scale)
		}
		return "numeric"
	case record.String:
		if c.Length > 0 && c.Length <= 10485760 {
			return fmt.Sprintf("varchar(%d)", c.Length)
		}
		return "text"
	case record.Bytes:
		return "bytea"
	case record.Date:
		return "date"
	case record.Time:
		return "time"
	case record.Timestamp:
		return "timestamp"
	case record.TimestampTZ:
		return "timestamptz"
	case record.Interval:
		return "interval"
	case record.JSON:
		return "jsonb"
	case record.UUID:
		return "uuid"
	case record.Bit:
		if c.Length > 0 {
			return fmt.Sprintf("bit varying(%d)", c.Length)
		}
		return "bit varying"
	default:
		return "text"
	}
}

// CreateTable creates schema.name with the given columns and primary key.
// Secondary indexes and foreign keys are added after the load.
func (p *PG) CreateTable(ctx context.Context, schema, name string, cols []record.Column, pk []string, sourceDialect string) error {
	// IF NOT EXISTS still races between concurrent sessions (unique_violation
	// on pg_namespace); losing that race means the schema exists.
	if _, err := p.Pool.Exec(ctx, "CREATE SCHEMA IF NOT EXISTS "+QuotePG(schema)); err != nil && !isDuplicate(err) {
		return fmt.Errorf("create schema %s: %w", schema, err)
	}
	sql := CreateTableSQL(schema, name, cols, pk, sourceDialect)
	if _, err := p.Pool.Exec(ctx, sql); err != nil && !isDuplicate(err) {
		return fmt.Errorf("create table %s.%s: %w", schema, name, err)
	}
	return nil
}

// CreateTableSQL renders the CREATE TABLE the sink would run.
func CreateTableSQL(schema, name string, cols []record.Column, pk []string, sourceDialect string) string {
	var defs []string
	pkSet := map[string]bool{}
	for _, k := range pk {
		pkSet[k] = true
	}
	for _, c := range cols {
		d := QuotePG(c.Name) + " " + PGType(c, sourceDialect)
		if c.AutoIncrement && pkSet[c.Name] && len(pk) == 1 && isIntType(c) {
			d += " GENERATED BY DEFAULT AS IDENTITY"
		} else if c.Default != "" && defaultPortable(c, sourceDialect) {
			d += " DEFAULT " + c.Default
		}
		if !c.Nullable || pkSet[c.Name] {
			d += " NOT NULL"
		}
		defs = append(defs, d)
	}
	if len(pk) > 0 {
		q := make([]string, len(pk))
		for i, k := range pk {
			q[i] = QuotePG(k)
		}
		defs = append(defs, fmt.Sprintf("CONSTRAINT %s PRIMARY KEY (%s)", QuotePG(Ident63(name+"_pkey")), strings.Join(q, ", ")))
	}
	return fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s.%s (\n  %s\n)", QuotePG(schema), QuotePG(name), strings.Join(defs, ",\n  "))
}

func isDuplicate(err error) bool {
	var pe *pgconn.PgError
	return errors.As(err, &pe) && (pe.Code == "23505" || pe.Code == "42P06" || pe.Code == "42P07")
}

func isIntType(c record.Column) bool {
	switch c.Type {
	case record.Int16, record.Int32, record.Int64, record.Uint64:
		return true
	}
	return false
}

func defaultPortable(c record.Column, dialect string) bool {
	if dialect == "postgres" {
		return !strings.Contains(c.Default, "::regclass") && c.Type != record.Other && c.Type != record.Enum
	}
	return true
}

// AddColumns adds columns that appeared mid-stream (e.g. from a script).
func (p *PG) AddColumns(ctx context.Context, t *Target, cols []record.Column) error {
	for _, c := range cols {
		q := fmt.Sprintf("ALTER TABLE %s ADD COLUMN IF NOT EXISTS %s %s", t.Ref(), QuotePG(c.Name), PGType(c, ""))
		if _, err := p.Pool.Exec(ctx, q); err != nil {
			return fmt.Errorf("add column %s.%s: %w", t.Display(), c.Name, err)
		}
		c.Nullable = true
		t.Columns[c.Name] = c
		t.Order = append(t.Order, c.Name)
	}
	return nil
}

// AlterColumnType converts an existing column to typ, casting its values
// (USING col::typ).
func (p *PG) AlterColumnType(ctx context.Context, t *Target, col, typ string) error {
	q := fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s TYPE %s USING %s::%s", t.Ref(), QuotePG(col), typ, QuotePG(col), typ)
	if _, err := p.Pool.Exec(ctx, q); err != nil {
		return fmt.Errorf("change type of %s.%s to %s: %w", t.Display(), col, typ, err)
	}
	c := t.Columns[col]
	c.NativeType = typ
	t.Columns[col] = c
	return nil
}

// AlterColumnTypeSQL renders the statement AlterColumnType runs.
func AlterColumnTypeSQL(t *Target, col, typ string) string {
	return fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s TYPE %s USING %s::%s", t.Ref(), QuotePG(col), typ, QuotePG(col), typ)
}

var pgTypeRe = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_ ]*(\([0-9 ,]+\))?( ?\[\])?$`)

// ValidPGType reports whether s looks like a PostgreSQL type name (e.g.
// "varchar(120)", "timestamp with time zone", "text[]") — nothing that
// could smuggle other SQL into DDL.
func ValidPGType(s string) bool { return pgTypeRe.MatchString(strings.TrimSpace(s)) }

// Truncate empties the table; cascade also truncates referencing tables.
func (p *PG) Truncate(ctx context.Context, t *Target, cascade bool) error {
	q := "TRUNCATE " + t.Ref()
	if cascade {
		q += " CASCADE"
	}
	_, err := p.Pool.Exec(ctx, q)
	return err
}

// WriteOptions tunes one write.
type WriteOptions struct {
	Mode            WriteMode
	Sanitize        bool
	DisableTriggers bool
	Dedupe          bool // keep the last row per key within the batch
	// ConflictCols overrides the conflict target (default: the primary key);
	// needs a unique constraint or index on exactly these columns.
	ConflictCols []string
	// NoUpdate lists columns a merge never overwrites (e.g. created_at).
	NoUpdate []string
}

// RowError pinpoints the row that made a write fail.
type RowError struct {
	Row int
	Err error
}

func (e *RowError) Error() string { return fmt.Sprintf("row %d: %v", e.Row, e.Err) }
func (e *RowError) Unwrap() error { return e.Err }

// Write loads rows (aligned with cols) into t in one transaction.
func (p *PG) Write(ctx context.Context, t *Target, cols []string, rows [][]any, o WriteOptions) (int64, error) {
	if len(rows) == 0 {
		return 0, nil
	}
	buf := copyBuffer(t, cols, rows, o.Sanitize)
	colList := quotedList(cols)

	conn, err := p.Pool.Acquire(ctx)
	if err != nil {
		return 0, err
	}
	defer conn.Release()
	tx, err := conn.Begin(ctx)
	if err != nil {
		return 0, err
	}
	defer tx.Rollback(context.WithoutCancel(ctx))
	if o.DisableTriggers {
		if _, err := tx.Exec(ctx, "SET LOCAL session_replication_role = replica"); err != nil {
			return 0, fmt.Errorf("disable triggers (needs superuser): %w", err)
		}
	}

	mode := o.Mode
	key := t.PK
	anyConflict := len(o.ConflictCols) == 1 && o.ConflictCols[0] == "*"
	if len(o.ConflictCols) > 0 && !anyConflict {
		key = o.ConflictCols
	}
	pkCovered := len(key) > 0
	for _, k := range key {
		if !contains(cols, k) {
			pkCovered = false
		}
	}
	if (mode == ModeMerge || mode == ModeMergeIgnore) && !pkCovered && !(anyConflict && mode == ModeMergeIgnore) {
		mode = ModeInsert
	}

	var n int64
	if mode == ModeCopy {
		tag, err := conn.Conn().PgConn().CopyFrom(ctx, bytes.NewReader(buf.Bytes()),
			fmt.Sprintf("COPY %s (%s) FROM STDIN", t.Ref(), colList))
		if err != nil {
			return 0, copyRowError(err)
		}
		n = tag.RowsAffected()
	} else {
		stg := stagingName(t, cols)
		if _, err := tx.Exec(ctx, fmt.Sprintf(
			"CREATE TEMP TABLE IF NOT EXISTS %s ON COMMIT DELETE ROWS AS SELECT %s FROM %s WITH NO DATA",
			QuotePG(stg), colList, t.Ref())); err != nil {
			return 0, fmt.Errorf("create staging table: %w", err)
		}
		if _, err := conn.Conn().PgConn().CopyFrom(ctx, bytes.NewReader(buf.Bytes()),
			fmt.Sprintf("COPY %s (%s) FROM STDIN", QuotePG(stg), colList)); err != nil {
			return 0, copyRowError(err)
		}
		sel := fmt.Sprintf("SELECT %s FROM %s", colList, QuotePG(stg))
		pkq := make([]string, len(key))
		for i, k := range key {
			pkq[i] = QuotePG(k)
		}
		if o.Dedupe && len(key) > 0 {
			sel = fmt.Sprintf("SELECT DISTINCT ON (%s) %s FROM %s ORDER BY %s, ctid DESC",
				strings.Join(pkq, ", "), colList, QuotePG(stg), strings.Join(pkq, ", "))
		}
		ins := fmt.Sprintf("INSERT INTO %s AS nifi_t (%s) %s", t.Ref(), colList, sel)
		switch mode {
		case ModeMerge:
			var sets, cur, inc []string
			for _, c := range cols {
				if !contains(key, c) && !contains(t.PK, c) && !contains(o.NoUpdate, c) {
					q := QuotePG(c)
					sets = append(sets, fmt.Sprintf("%s = EXCLUDED.%s", q, q))
					// compared as text: works for every type, including json
					cur = append(cur, "nifi_t."+q+"::text")
					inc = append(inc, "EXCLUDED."+q+"::text")
				}
			}
			if len(sets) == 0 {
				ins += fmt.Sprintf(" ON CONFLICT (%s) DO NOTHING", strings.Join(pkq, ", "))
			} else {
				// Only rewrite rows whose values changed: re-running a load
				// over an already-migrated, indexed table then costs a
				// comparison per row instead of a new row version plus an
				// update of every index.
				ins += fmt.Sprintf(" ON CONFLICT (%s) DO UPDATE SET %s WHERE (%s) IS DISTINCT FROM (%s)",
					strings.Join(pkq, ", "), strings.Join(sets, ", "), strings.Join(cur, ", "), strings.Join(inc, ", "))
			}
		case ModeMergeIgnore:
			if anyConflict {
				// any unique violation (PK or unique index) skips the row
				ins += " ON CONFLICT DO NOTHING"
			} else {
				ins += fmt.Sprintf(" ON CONFLICT (%s) DO NOTHING", strings.Join(pkq, ", "))
			}
		}
		tag, err := tx.Exec(ctx, ins)
		if err != nil {
			return 0, err
		}
		n = tag.RowsAffected()
	}
	if err := tx.Commit(ctx); err != nil {
		return 0, err
	}
	return n, nil
}

func contains(s []string, v string) bool {
	for _, x := range s {
		if x == v {
			return true
		}
	}
	return false
}

// copyBuffer encodes rows (aligned with cols) in PostgreSQL's text COPY format.
func copyBuffer(t *Target, cols []string, rows [][]any, sanitize bool) *bytes.Buffer {
	enc := make([]encoder, len(cols))
	for i, c := range cols {
		enc[i] = encoderFor(t.Columns[c], sanitize)
	}
	var buf bytes.Buffer
	buf.Grow(len(rows) * len(cols) * 12)
	for _, r := range rows {
		for i := range cols {
			if i > 0 {
				buf.WriteByte('\t')
			}
			var v any
			if i < len(r) {
				v = r[i]
			}
			if v == nil {
				buf.WriteString(`\N`)
				continue
			}
			enc[i](&buf, v)
		}
		buf.WriteByte('\n')
	}
	return &buf
}

func quotedList(cols []string) string {
	q := make([]string, len(cols))
	for i, c := range cols {
		q[i] = QuotePG(c)
	}
	return strings.Join(q, ", ")
}

// DeleteByKey removes every row of t whose key columns match one of rows
// (aligned with key). The keys are staged with COPY, so a batch of deletes is
// one statement however many rows it carries.
func (p *PG) DeleteByKey(ctx context.Context, t *Target, key []string, rows [][]any, o WriteOptions) (int64, error) {
	if len(rows) == 0 {
		return 0, nil
	}
	if len(key) == 0 {
		return 0, fmt.Errorf("%s has no primary key: there is nothing to match a deleted row on", t.Display())
	}
	buf := copyBuffer(t, key, rows, o.Sanitize)
	colList := quotedList(key)

	conn, err := p.Pool.Acquire(ctx)
	if err != nil {
		return 0, err
	}
	defer conn.Release()
	tx, err := conn.Begin(ctx)
	if err != nil {
		return 0, err
	}
	defer tx.Rollback(context.WithoutCancel(ctx))
	if o.DisableTriggers {
		if _, err := tx.Exec(ctx, "SET LOCAL session_replication_role = replica"); err != nil {
			return 0, fmt.Errorf("disable triggers (needs superuser): %w", err)
		}
	}
	stg := stagingName(t, key) + "_del"
	if _, err := tx.Exec(ctx, fmt.Sprintf(
		"CREATE TEMP TABLE IF NOT EXISTS %s ON COMMIT DELETE ROWS AS SELECT %s FROM %s WITH NO DATA",
		QuotePG(stg), colList, t.Ref())); err != nil {
		return 0, fmt.Errorf("create staging table: %w", err)
	}
	if _, err := conn.Conn().PgConn().CopyFrom(ctx, bytes.NewReader(buf.Bytes()),
		fmt.Sprintf("COPY %s (%s) FROM STDIN", QuotePG(stg), colList)); err != nil {
		return 0, copyRowError(err)
	}
	on := make([]string, len(key))
	for i, k := range key {
		on[i] = fmt.Sprintf("nifi_t.%s = nifi_d.%s", QuotePG(k), QuotePG(k))
	}
	tag, err := tx.Exec(ctx, fmt.Sprintf("DELETE FROM %s AS nifi_t USING %s AS nifi_d WHERE %s",
		t.Ref(), QuotePG(stg), strings.Join(on, " AND ")))
	if err != nil {
		return 0, err
	}
	if err := tx.Commit(ctx); err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

func stagingName(t *Target, cols []string) string {
	h := fnv.New64a()
	io.WriteString(h, t.Schema+"."+t.Name+"|"+strings.Join(cols, ","))
	return fmt.Sprintf("nifi_stg_%x", h.Sum64())
}

var copyLineRe = regexp.MustCompile(`line (\d+)`)

func copyRowError(err error) error {
	var pe *pgconn.PgError
	if errors.As(err, &pe) {
		if m := copyLineRe.FindStringSubmatch(pe.Where); m != nil {
			if n, e := strconv.Atoi(m[1]); e == nil && n > 0 {
				return &RowError{Row: n - 1, Err: err}
			}
		}
	}
	return err
}

// ErrorClass buckets a write error.
type ErrorClass int

const (
	ErrData      ErrorClass = iota // bad row(s): isolate and dead-letter
	ErrTransient                   // retry with backoff
	ErrFatal                       // stop the run
)

// Classify decides how a write error is handled.
func Classify(err error) ErrorClass {
	var pe *pgconn.PgError
	if errors.As(err, &pe) {
		switch {
		case strings.HasPrefix(pe.Code, "22"), strings.HasPrefix(pe.Code, "23"), pe.Code == "21000", pe.Code == "54000":
			return ErrData
		case strings.HasPrefix(pe.Code, "08"), strings.HasPrefix(pe.Code, "40"), strings.HasPrefix(pe.Code, "53"),
			strings.HasPrefix(pe.Code, "57P"), pe.Code == "55P03":
			return ErrTransient
		}
		return ErrFatal
	}
	var ne net.Error
	if errors.As(err, &ne) || errors.Is(err, io.EOF) || errors.Is(err, io.ErrUnexpectedEOF) {
		return ErrTransient
	}
	if strings.Contains(err.Error(), "conn closed") || strings.Contains(err.Error(), "connection reset") {
		return ErrTransient
	}
	return ErrFatal
}

// IsCardinality reports a duplicate key inside one merge batch.
func IsCardinality(err error) bool {
	var pe *pgconn.PgError
	return errors.As(err, &pe) && pe.Code == "21000"
}

type encoder func(*bytes.Buffer, any)

func encoderFor(c record.Column, sanitize bool) encoder {
	str := func(b *bytes.Buffer, s string) {
		if sanitize {
			s = cleanString(s)
		}
		copyEscape(b, s)
	}
	switch c.Type {
	case record.Bytes:
		return func(b *bytes.Buffer, v any) {
			var raw []byte
			switch x := v.(type) {
			case []byte:
				raw = x
			case string:
				raw = []byte(x)
			default:
				raw = []byte(fmt.Sprint(x))
			}
			b.WriteString(`\\x`)
			b.WriteString(hex.EncodeToString(raw))
		}
	case record.Bool:
		return func(b *bytes.Buffer, v any) {
			switch x := v.(type) {
			case bool:
				b.WriteString(pick(x, "t", "f"))
			case int64:
				b.WriteString(pick(x != 0, "t", "f"))
			case float64:
				b.WriteString(pick(x != 0, "t", "f"))
			default:
				str(b, toText(x))
			}
		}
	case record.Int16, record.Int32, record.Int64, record.Uint64, record.Year, record.Float32, record.Float64, record.Decimal:
		return func(b *bytes.Buffer, v any) {
			if x, ok := v.(bool); ok {
				b.WriteString(pick(x, "1", "0"))
				return
			}
			str(b, toText(v))
		}
	case record.Date:
		return timeEnc(str, "2006-01-02")
	case record.Timestamp:
		return timeEnc(str, "2006-01-02 15:04:05.999999")
	case record.TimestampTZ:
		return timeEnc(str, "2006-01-02 15:04:05.999999Z07:00")
	case record.Time:
		return timeEnc(str, "15:04:05.999999")
	case record.JSON:
		return func(b *bytes.Buffer, v any) {
			s := toText(v)
			if sanitize {
				s = strings.ReplaceAll(s, "\\u0000", "")
			}
			str(b, s)
		}
	default:
		return func(b *bytes.Buffer, v any) {
			if raw, ok := v.([]byte); ok {
				str(b, string(raw))
				return
			}
			str(b, toText(v))
		}
	}
}

func timeEnc(str func(*bytes.Buffer, string), layout string) encoder {
	return func(b *bytes.Buffer, v any) {
		if t, ok := v.(time.Time); ok {
			b.WriteString(t.Format(layout))
			return
		}
		str(b, toText(v))
	}
}

func toText(v any) string {
	switch x := v.(type) {
	case string:
		return x
	case []byte:
		return string(x)
	case int64:
		return strconv.FormatInt(x, 10)
	case int:
		return strconv.Itoa(x)
	case int32:
		return strconv.FormatInt(int64(x), 10)
	case uint64:
		return strconv.FormatUint(x, 10)
	case float64:
		switch {
		case math.IsNaN(x):
			return "NaN"
		case math.IsInf(x, 1):
			return "Infinity"
		case math.IsInf(x, -1):
			return "-Infinity"
		}
		return strconv.FormatFloat(x, 'g', -1, 64)
	case float32:
		return strconv.FormatFloat(float64(x), 'g', -1, 32)
	case bool:
		return pick(x, "true", "false")
	case time.Time:
		return x.Format(time.RFC3339Nano)
	case map[string]any, []any:
		j, _ := json.Marshal(x)
		return string(j)
	default:
		if j, err := json.Marshal(x); err == nil && (len(j) > 0 && (j[0] == '{' || j[0] == '[')) {
			return string(j)
		}
		return fmt.Sprint(x)
	}
}

func cleanString(s string) string {
	if strings.IndexByte(s, 0) >= 0 {
		s = strings.ReplaceAll(s, "\x00", "")
	}
	if !utf8.ValidString(s) {
		s = strings.ToValidUTF8(s, "�")
	}
	return s
}

func copyEscape(b *bytes.Buffer, s string) {
	for i := 0; i < len(s); i++ {
		switch c := s[i]; c {
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteByte(c)
		}
	}
}

// Ident63 truncates an identifier to PostgreSQL's 63-byte limit, suffixing a
// hash when it had to cut so distinct long names stay distinct.
func Ident63(s string) string {
	if len(s) <= 63 {
		return s
	}
	h := fnv.New32a()
	io.WriteString(h, s)
	return fmt.Sprintf("%s_%08x", s[:54], h.Sum32())
}

// CreateIndex builds a secondary index if one of that name does not exist.
func (p *PG) CreateIndex(ctx context.Context, t *Target, name string, cols []string, unique bool) error {
	q := make([]string, len(cols))
	for i, c := range cols {
		q[i] = QuotePG(c)
	}
	kw := "INDEX"
	if unique {
		kw = "UNIQUE INDEX"
	}
	_, err := p.Pool.Exec(ctx, fmt.Sprintf("CREATE %s IF NOT EXISTS %s ON %s (%s)", kw, QuotePG(Ident63(name)), t.Ref(), strings.Join(q, ", ")))
	return err
}

// AddForeignKey adds an FK as NOT VALID, then validates it. A validation
// failure leaves the constraint in place (enforced for new rows) and is
// returned so the caller can warn about orphaned rows.
func (p *PG) AddForeignKey(ctx context.Context, t *Target, fk record.ForeignKey, refSchema, refTable string) (validated bool, err error) {
	name := Ident63(fk.Name)
	var exists bool
	if err := p.Pool.QueryRow(ctx, `SELECT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid=$1::regclass AND conname=$2)`,
		t.Ref(), name).Scan(&exists); err != nil {
		return false, err
	}
	if !exists {
		q := func(xs []string) string {
			out := make([]string, len(xs))
			for i, x := range xs {
				out[i] = QuotePG(x)
			}
			return strings.Join(out, ", ")
		}
		sql := fmt.Sprintf("ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s.%s (%s) ON DELETE %s ON UPDATE %s NOT VALID",
			t.Ref(), QuotePG(name), q(fk.Columns), QuotePG(refSchema), QuotePG(refTable), q(fk.RefColumns),
			fkAction(fk.OnDelete), fkAction(fk.OnUpdate))
		if _, err := p.Pool.Exec(ctx, sql); err != nil {
			return false, err
		}
	}
	if _, err := p.Pool.Exec(ctx, fmt.Sprintf("ALTER TABLE %s VALIDATE CONSTRAINT %s", t.Ref(), QuotePG(name))); err != nil {
		return false, fmt.Errorf("left NOT VALID (existing rows violate it): %s", DescribeError(err))
	}
	return true, nil
}

func fkAction(a string) string {
	switch strings.ToUpper(a) {
	case "CASCADE", "SET NULL", "SET DEFAULT", "RESTRICT":
		return strings.ToUpper(a)
	default:
		return "NO ACTION"
	}
}

// ResetSequence aligns an identity/serial sequence with MAX(col).
func (p *PG) ResetSequence(ctx context.Context, t *Target, col string) error {
	_, err := p.Pool.Exec(ctx, fmt.Sprintf(`SELECT setval(s, COALESCE((SELECT MAX(%[1]s) FROM %[2]s), 1), (SELECT MAX(%[1]s) FROM %[2]s) IS NOT NULL)
		FROM pg_get_serial_sequence($1, $2) s WHERE s IS NOT NULL`, QuotePG(col), t.Ref()), t.Ref(), col)
	return err
}

// Analyze refreshes planner statistics after a bulk load.
func (p *PG) Analyze(ctx context.Context, t *Target) error {
	_, err := p.Pool.Exec(ctx, "ANALYZE "+t.Ref())
	return err
}

// Exec runs a statement (used for user SQL hooks).
func (p *PG) Exec(ctx context.Context, sql string) error {
	_, err := p.Pool.Exec(ctx, sql, pgx.QueryExecModeSimpleProtocol)
	return err
}

// Describe renders a database error with its detail and SQLSTATE.
func DescribeError(err error) string {
	var pe *pgconn.PgError
	if errors.As(err, &pe) {
		msg := pe.Message
		if pe.Detail != "" {
			msg += " — " + pe.Detail
		}
		if pe.ColumnName != "" {
			msg += " (column " + pe.ColumnName + ")"
		}
		return msg + " [" + pe.Code + "]"
	}
	var re *RowError
	if errors.As(err, &re) {
		return DescribeError(re.Err)
	}
	return err.Error()
}

// DropNotNull relaxes NOT NULL on columns (used when a created table gains a
// feeder that doesn't provide them).
func (p *PG) DropNotNull(ctx context.Context, t *Target, cols []string) error {
	for _, c := range cols {
		if _, err := p.Pool.Exec(ctx, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s DROP NOT NULL", t.Ref(), QuotePG(c))); err != nil {
			return fmt.Errorf("relax NOT NULL on %s.%s: %w", t.Display(), c, err)
		}
		col := t.Columns[c]
		col.Nullable = true
		t.Columns[c] = col
	}
	return nil
}
